// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnmzqtthnyiiahhnqkxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ubXpxdHRobnlpaWFoaG5xa3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MzIwMzEsImV4cCI6MjA3MjAwODAzMX0.JHkGi37_0scfouDrhsGo7QNnNpOFGHias8JsIvRSZEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});