// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thdyuihbgyinxqjvzrbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoZHl1aWhiZ3lpbnhxanZ6cmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Mzg3NTAsImV4cCI6MjA3NDUxNDc1MH0.ll3uPlOgiOe-wuWWLHD2cJwRL4JR7Rd_m0SpNqLcMLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});